<template>
  <div class="min-h-screen bg-gray-100 flex items-center justify-center py-8 px-4 sm:px-6 lg:px-8">
    <div
      class="max-w-4xl w-full space-y-8 transition duration-500 ease-in-out transform hover:scale-105 bg-white shadow-md rounded-lg overflow-hidden p-6 text-center">
      <h1 class="text-4xl font-extrabold mb-6 text-indigo-900">About Paris 2024 Olympics Countries</h1>
      <p class="text-xl text-gray-700">This application provides information about the participating countries in the
        Paris 2024 Olympics.</p>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Event Details</h2>
        <p class="text-lg text-gray-600">The Paris 2024 Olympic Games will take place from July 26 to August 11, 2024.
          The Paralympic Games will follow from August 28 to September 8, 2024.</p>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Participating Countries</h2>
        <p class="text-lg text-gray-600">Over 200 National Olympic Committees (NOCs) are expected to participate in the
          Paris 2024 Olympics, representing athletes from around the world.</p>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Venue Information</h2>
        <p class="text-lg text-gray-600">The games will feature venues across Paris and its surrounding regions,
          including iconic sites such as the Eiffel Tower and new facilities like the Aquatic Center.</p>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Highlights</h2>
        <ul class="list-disc list-inside text-left text-gray-600">
          <li>New sports events like skateboarding, sport climbing, surfing, and karate will make their Olympic debut.
          </li>
          <li>The opening ceremony will be held at the Stade de France on July 26, 2024.</li>
          <li>Paris 2024 aims to be the most sustainable Olympic Games ever hosted, with a focus on reducing carbon
            emissions and promoting environmental sustainability.</li>
        </ul>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Sustainability Efforts</h2>
        <p class="text-lg text-gray-600">Paris 2024 is committed to hosting the most environmentally friendly Games to
          date:</p>
        <ul class="list-disc list-inside text-left text-gray-600 mt-2">
          <li><strong>Carbon Neutrality:</strong> The Games aim to offset all greenhouse gas emissions generated by the
            organization of the Games.</li>
          <li><strong>Reuse and Recycling:</strong> Many venues are temporary or reused, and materials are recycled
            wherever possible.</li>
          <li><strong>Eco-Friendly Venues:</strong> New venues are designed to meet high environmental standards.</li>
        </ul>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Accommodation</h2>
        <p class="text-lg text-gray-600">Athletes and officials will stay in accommodations that are eco-friendly and
          sustainable:</p>
        <ul class="list-disc list-inside text-left text-gray-600 mt-2">
          <li><strong>Villages Olympiques:</strong> Athlete villages are designed to minimize their environmental
            impact.</li>
          <li><strong>Sustainable Materials:</strong> Accommodations use sustainable building materials and practices.
          </li>
        </ul>
      </section>

      <section class="space-y-4">
        <h2 class="text-2xl font-bold text-indigo-800">Transportation</h2>
        <p class="text-lg text-gray-600">Efforts are being made to reduce transportation-related emissions:</p>
        <ul class="list-disc list-inside text-left text-gray-600 mt-2">
          <li><strong>Public Transport:</strong> Encouraging the use of public transport for spectators and
            participants.</li>
          <li><strong>Electric Vehicles:</strong> Using electric vehicles for official transportation where possible.
          </li>
        </ul>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts"></script>
